---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName : sm-pipelines-
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: aws_account_id
        value: 100000000002
      - name: aws_region_name
        value: us-west-2
      - name: pipeline_name
        value: MyPipeline
  workflowTemplateRef:
    name: sm-pipelines