apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: aws-glue-job
  namespace: argo
  annotations:
    workflows.argoproj.io/description: |
      Execute AWS Glue job run.
    workflows.argoproj.io/maintainer: '@greenpau'
    workflows.argoproj.io/tags: aws, aws glue
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  activeDeadlineSeconds: 600
  entrypoint: main
  serviceAccountName: awf-aws-executor-plugin
  arguments:
    parameters:
      - name: aws_account_id
        value: 100000000002
      - name: aws_region_name
        value: us-west-2
      - name: job_name
        value: MyGlueJob
  templates:
    - name: main
      steps:
        - - name: validate-glue-job
            template: validate_glue_job
        - - name: execute-glue-job
            template: execute_glue_job
    - name: validate_glue_job
      plugin:
        awf-aws-plugin:
          action: "validate"
          service: "aws_glue"
          account_id: "{{workflow.parameters.aws_account_id}}"
          region_name: "{{workflow.parameters.aws_region_name}}"
          job_name: "{{workflow.parameters.job_name}}"
    - name: execute_glue_job
      plugin:
        awf-aws-plugin:
          action: "execute"
          service: "aws_glue"
          account_id: "{{workflow.parameters.aws_account_id}}"
          region_name: "{{workflow.parameters.aws_region_name}}"
          job_name: "{{workflow.parameters.job_name}}"