apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: aws-step-function
  namespace: argo
  annotations:
    workflows.argoproj.io/description: |
      Execute AWS Step Functions state machine execution.
    workflows.argoproj.io/maintainer: '@greenpau'
    workflows.argoproj.io/tags: aws, aws step functions
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  activeDeadlineSeconds: 600
  entrypoint: main
  serviceAccountName: awf-aws-executor-plugin
  arguments:
    parameters:
      - name: aws_account_id
        value: 100000000002
      - name: aws_region_name
        value: us-west-2
      - name: step_function_name
        value: MyStepFunction
  templates:
    - name: main
      steps:
        - - name: validate-step-function
            template: validate_step_function
        - - name: execute-step-function
            template: execute_step_function
    - name: validate_step_function
      plugin:
        awf-aws-plugin:
          action: "validate"
          service: "aws_step_functions"
          account_id: "{{workflow.parameters.aws_account_id}}"
          region_name: "{{workflow.parameters.aws_region_name}}"
          step_function_name: "{{workflow.parameters.step_function_name}}"
    - name: execute_step_function
      plugin:
        awf-aws-plugin:
          action: "execute"
          service: "aws_step_functions"
          account_id: "{{workflow.parameters.aws_account_id}}"
          region_name: "{{workflow.parameters.aws_region_name}}"
          step_function_name: "{{workflow.parameters.step_function_name}}"