---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awf-aws-executor-plugin
  namespace: argo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::100000000002:role/awf-aws-executor-plugin
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: awf-aws-executor-plugin.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: "awf-aws-executor-plugin"
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: default.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awf-aws-executor-role
  namespace: argo
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtasksets
  - workflowtasksets/status
  verbs:
  - get
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awf-aws-executor-plugin-cluster-role-bind
subjects:
- kind: ServiceAccount
  name: awf-aws-executor-plugin
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awf-aws-executor-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awf-aws-executor-plugin-role-bind
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
  - kind: ServiceAccount
    name: awf-aws-executor-plugin
    namespace: argo
---
apiVersion: v1
data:
  sidecar.automountServiceAccountToken: "true"
  sidecar.container: |
    image: ghcr.io/greenpau/argo-workflows-aws-plugin:latest
    command: ['argo-workflows-aws-plugin', '--debug']
    name: awf-aws
    ports:
    - containerPort: 7492
    resources:
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 32Mi
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop:
        - ALL
kind: ConfigMap
metadata:
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
  annotations:
    workflows.argoproj.io/description: |
      This plugin executes various AWS Services, e.g. SageMaker Pipelines, Glue, etc.

      For SageMaker Pipelines, it accepts the name of a SageMaker Pipeline as an input
      and triggers the execution of the pipeline. Subsequently, it checks the status
      of the pipeline execution using the execution id.
    workflows.argoproj.io/version: '>= v3.4'
  name: awf-aws
  namespace: argo