---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sagemaker-pipeline-exec-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: validate-pipeline
            template: pipeline-validate

        - - name: pre-hello
            template: hello

        - - name: execute-pipeline
            template: pipeline-execute
            arguments:
              parameters:
                - name: pipeline_arn
                  value: "foo:bar"

        - - name: post-hello
            template: hello

    - name: pipeline-validate
      plugin:
        awf-aws-plugin:
          validate:
            config:
              token: amz-smp-token

    - name: pipeline-execute
      inputs:
        parameters:
          - name: pipeline_arn
      plugin:
        awf-aws-plugin:
          execute:
            config:
              token: amz-smp-token

    - name: hello
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["hello world"]
